openapi: 3.0.0
paths:
  /api/v1:
    get:
      operationId: AppController_getAll
      parameters: []
      responses:
        '200':
          description: ''
    post:
      operationId: AppController_create
      parameters: []
      responses:
        '201':
          description: ''
    delete:
      operationId: AppController_delete
      parameters: []
      responses:
        '200':
          description: ''
  /api/v2:
    get:
      operationId: AppController_getAll
      parameters: []
      responses:
        '200':
          description: ''
    post:
      operationId: AppController_create
      parameters: []
      responses:
        '201':
          description: ''
    delete:
      operationId: AppController_delete
      parameters: []
      responses:
        '200':
          description: ''
  /api/v1/companies:
    post:
      operationId: CompaniesController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCompanyDto'
      responses:
        '201':
          description: ''
    get:
      operationId: CompaniesController_findAll
      parameters:
        - name: page
          required: true
          in: query
          schema:
            type: number
        - name: limit
          required: true
          in: query
          schema:
            type: number
      responses:
        '200':
          description: ''
  /api/v2/companies:
    post:
      operationId: CompaniesController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCompanyDto'
      responses:
        '201':
          description: ''
    get:
      operationId: CompaniesController_findAll
      parameters:
        - name: page
          required: true
          in: query
          schema:
            type: number
        - name: limit
          required: true
          in: query
          schema:
            type: number
      responses:
        '200':
          description: ''
  /api/v1/companies/{id}:
    get:
      operationId: CompaniesController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /api/v2/companies/{id}:
    get:
      operationId: CompaniesController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /api/v1/companies/{_id}:
    patch:
      operationId: CompaniesController_update
      parameters:
        - name: _id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCompanyDto'
      responses:
        '200':
          description: ''
    delete:
      operationId: CompaniesController_remove
      parameters:
        - name: _id
          required: true
          in: path
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: ''
  /api/v2/companies/{_id}:
    patch:
      operationId: CompaniesController_update
      parameters:
        - name: _id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCompanyDto'
      responses:
        '200':
          description: ''
    delete:
      operationId: CompaniesController_remove
      parameters:
        - name: _id
          required: true
          in: path
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: ''
  /api/v1/users:
    post:
      operationId: UsersController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: ''
    get:
      operationId: UsersController_findAll
      parameters:
        - name: page
          required: true
          in: query
          schema:
            type: number
        - name: limit
          required: true
          in: query
          schema:
            type: number
        - name: sort
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
  /api/v2/users:
    post:
      operationId: UsersController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: ''
    get:
      operationId: UsersController_findAll
      parameters:
        - name: page
          required: true
          in: query
          schema:
            type: number
        - name: limit
          required: true
          in: query
          schema:
            type: number
        - name: sort
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
  /api/v1/users/{id}:
    get:
      operationId: UsersController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
    patch:
      operationId: UsersController_update
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserDto'
      responses:
        '200':
          description: ''
    delete:
      operationId: UsersController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /api/v2/users/{id}:
    get:
      operationId: UsersController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
    patch:
      operationId: UsersController_update
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserDto'
      responses:
        '200':
          description: ''
    delete:
      operationId: UsersController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /api/v1/auth/sign-up:
    post:
      operationId: AuthController_signUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupDto'
      responses:
        '201':
          description: ''
  /api/v2/auth/sign-up:
    post:
      operationId: AuthController_signUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupDto'
      responses:
        '201':
          description: ''
  /api/v1/auth/sign-in:
    post:
      operationId: AuthController_signIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '201':
          description: ''
  /api/v2/auth/sign-in:
    post:
      operationId: AuthController_signIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '201':
          description: ''
  /api/v1/auth/me:
    get:
      operationId: AuthController_handleGetAccount
      parameters: []
      responses:
        '200':
          description: ''
  /api/v2/auth/me:
    get:
      operationId: AuthController_handleGetAccount
      parameters: []
      responses:
        '200':
          description: ''
  /api/v1/auth/refresh-token:
    get:
      operationId: AuthController_handleRefreshToken
      parameters: []
      responses:
        '200':
          description: ''
  /api/v2/auth/refresh-token:
    get:
      operationId: AuthController_handleRefreshToken
      parameters: []
      responses:
        '200':
          description: ''
  /api/v1/auth/logout:
    post:
      operationId: AuthController_handleLogout
      parameters: []
      responses:
        '201':
          description: ''
  /api/v2/auth/logout:
    post:
      operationId: AuthController_handleLogout
      parameters: []
      responses:
        '201':
          description: ''
info:
  title: Cats example
  description: The cats API description
  version: '1.0'
  contact: {}
tags:
  - name: cats
    description: ''
servers: []
components:
  schemas:
    CreateCompanyDto:
      type: object
      properties: {}
    UpdateCompanyDto:
      type: object
      properties: {}
    CreateUserDto:
      type: object
      properties: {}
    UpdateUserDto:
      type: object
      properties: {}
    SignupDto:
      type: object
      properties: {}
    LoginDto:
      type: object
      properties: {}
