steps:
  # Bước 1: Cài đặt các package cho NestJS bằng Yarn
  - name: 'node:20'  # Sử dụng node phiên bản 20
    entrypoint: 'yarn'
    args: ['install']

  # Bước 2: Build ứng dụng với Yarn
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['build']

  # Bước 3: Triển khai ứng dụng lên Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

#images:
#  - 'asia/asia.gcr.io'  # Lưu trữ Docker image (tuỳ chọn)

options:
  machineType: 'e2-standard-2'
  logging: CLOUD_LOGGING_ONLY