steps:
  # Bước 1: Lấy code từ GitHub
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'git'
    args: ['clone', 'https://github.com/dinhbach306/nestjs-basic']

  # Bước 2: Cài đặt các package cho NestJS bằng Yarn
  - name: 'node:20'  # Sử dụng node phiên bản 16
    entrypoint: 'yarn'
    args: ['install']

  # Bước 3: Build ứng dụng với Yarn
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['run', 'build']

  # Bước 4: Triển khai ứng dụng lên Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

images:
  - 'gcr.io/massive-pen-298613/nestjs-app'  # Lưu trữ Docker image (tuỳ chọn)
