steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  
  # Run tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']
  
  # Build the application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  
  # Deploy to Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

# Thêm các bước khác nếu cần

# Optionally, you can specify which files to include in the build
# This is useful if you want to ignore certain files or directories
# artifacts:
#   objects:
#     location: 'gs://${PROJECT_ID}-artifacts'
#     paths: ['app.yaml', 'package.json', 'dist/**']