steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Setting environment variables"
        export DATABASE_URL=${_DATABASE_URL}
        export JWT_EXPIRES_IN=${_JWT_EXPIRES_IN}
        export JWT_KEY_SECRET=${_JWT_KEY_SECRET}

        # Run build commands (e.g., for Node.js or other environments)
        yarn install
        yarn run build

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']

#images:
#  - 'asia/asia.gcr.io'  # Lưu trữ Docker image (tuỳ chọn)

options:
  logging: CLOUD_LOGGING_ONLY